version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=MyStrongPass123!
      - ORACLE_PDB=FREEPDB1  # Nombre correcto de la PDB
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/MyStrongPass123!@localhost:1521/FREEPDB1"]  # Usar FREEPDB1
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 300s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'

volumes:
  oracle_data: